### ISSUE TITLE
daemon quits abnormally for ProQ3

### ISSUE THREAD

**Issue by nanjiangshu** [NBISweden/web_proq3#24]
The daemon qd_fe quits abnormally.

Error message from the log

```
Traceback (most recent call last):
  File "/big/server/var/www/web_proq3/proj/pred/app/qd_fe.py", line 1770, in <module>
    sys.exit(main(g_params))
  File "/big/server/var/www/web_proq3/proj/pred/app/qd_fe.py", line 1722, in main
    GetResult(jobid, query_para) # the start tagfile is written when got the first result
  File "/big/server/var/www/web_proq3/proj/pred/app/qd_fe.py", line 1063, in GetResult
    if status != "Running" and time_in_remote_queue > g_params['MAX_TIME_IN_REMOTE_QUEUE']:
UnboundLocalError: local variable 'status' referenced before assignment
```

**Comment by nanjiangshu** [comment]
The problem is solved
